# Site settings
title:            huha123 (bokyun) - Web Developer
description:      "huha123 profile"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://huha123.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username:         huha123
user_title:       huha123
email:            huha3213@gmail.com
twitter_username: ""
github_username:  huha123
gplus_username:   bokyunKo
disqus_username:  ""
profile_picture:  assets/img/3696779939_bc3255df_Download_2015_05_27_18_55_15.jpg

# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        /:title/


# html minify
compress_html:
  clippings:      all
  comments:       all
  endings:        []
  profile:        false

# Links to include in menu navigation
links:
  # - title:      home
  #   url:        /
  # - title:      my posts
  #   url:        /posts
  # - title:      series
  #   url:        /series
  # - title:      tags
  #   url:        /tags
  - title:        about me
    url:          /about
# projects in header index
projects:
  - name:         sound cloud challange - follow maze
    url:          https://github.com/huha123/soundcloud-challange
# exclude my node related stuff
exclude:          ['package.json', 'src', 'node_modules']
